context:
  version: "0.6.3"

package:
  name: convco
  version: ${{ version }}

source:
  url: https://github.com/convco/convco/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ea178bb268e45d507fd358e391fd6bbb552b8d9f6801f0193b4422e172fc6917

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - script:
      - convco --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Conventional commits, changelog, versioning, validation
  homepage: https://github.com/convco/convco
  repository: https://github.com/convco/convco

extra:
  recipe-maintainers:
    - danielnachun
